# Generated by Django 4.1.7 on 2023-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='colour_theme',
            field=models.CharField(default='yellow-theme', max_length=14),
        ),
    ]
