# Generated by Django 4.1.7 on 2023-02-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_colour_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
