# Generated by Django 4.1.7 on 2023-02-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_created',
            new_name='last_updated',
        ),
    ]
