# Generated by Django 4.1.7 on 2023-03-01 09:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_colour_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
