# Generated by Django 4.1.7 on 2023-03-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
