# Generated by Django 4.1.7 on 2023-03-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
