# Generated by Django 4.1.7 on 2023-03-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_alter_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
