# Generated by Django 4.1.7 on 2023-03-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_alter_image_alt_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_theme', models.CharField(choices=[('light-mode', 'light'), ('dark-mode', 'dark')], default='light-mode', max_length=10)),
            ],
        ),
    ]
