# Generated by Django 4.1.7 on 2023-03-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_displaymode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displaymode',
            old_name='colour_theme',
            new_name='display_mode',
        ),
    ]
